[profile.default]
solc_version = "0.8.19"
src = 'src'
out = 'out'
libs = ['lib']
optimizer_runs = 1000
verbosity = 1
fs_permissions = [{ access = "read-write", path = "./" }]


[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
goerli = "${RPC_URL_GOERLI}"
hyperspace = "${RPC_URL_HYPERSPACE}"
sepolia = "${RPC_URL_SEPOLIA}"
fuji = "${RPC_URL_FUJI}"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
goerli = { key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api" }
sepolia = { key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.etherscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
